image: gradle:jdk11
# image: gradle:jdk8

stages:
  - build

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main

after_script:
  - echo "Ation End CI"
