#该工作流将与Gradle一起构建一个Java项目
#有关更多信息，请参阅：https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
    # name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
        # java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Ation
        path: build/libs/*.jar
